const SALESFORCE_LOGIN_URL = process.env.SALESFORCE_LOGIN_URL || "https://login.salesforce.com";

const SALESFORCE_API_VERSION = process.env.SALESFORCE_API_VERSION || "v66.0";

const SALESFORCE_CALLBACK_URL = process.env.SALESFORCE_CALLBACK_URL;

const SALESFORCE_CLIENT_ID = process.env.SALESFORCE_CLIENT_ID;

const SALESFORCE_CLIENT_SECRET = process.env.SALESFORCE_CLIENT_SECRET;

module.exports = {
SALESFORCE_LOGIN_URL, 
SALESFORCE_API_VERSION, 
SALESFORCE_CALLBACK_URL, 
SALESFORCE_CLIENT_ID, 
SALESFORCE_CLIENT_SECRET }